# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "knife-parallel-ec2"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christian Paredes"]
  s.date = "2012-02-08"
  s.description = "Spawns EC2 servers in parallel with Knife by using the parallel gem."
  s.email = "ian@shopply.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/chef/knife/parallel_ec2_server_create.rb",
    "test/helper.rb",
    "test/test_knife-parallel-ec2.rb"
  ]
  s.homepage = "http://github.com/cparedes/knife-parallel-ec2"
  s.licenses = ["Apache v2"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Spawn EC2 servers in parallel using Knife."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<parallel>, [">= 0"])
      s.add_runtime_dependency(%q<chef>, [">= 0.10.0"])
      s.add_runtime_dependency(%q<knife-ec2>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.1"])
    else
      s.add_dependency(%q<parallel>, [">= 0"])
      s.add_dependency(%q<chef>, [">= 0.10.0"])
      s.add_dependency(%q<knife-ec2>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.1"])
    end
  else
    s.add_dependency(%q<parallel>, [">= 0"])
    s.add_dependency(%q<chef>, [">= 0.10.0"])
    s.add_dependency(%q<knife-ec2>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.1"])
  end
end

